<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="1" disabled="0" errors="0" timestamp="2016-01-09T19:19:49" time="0.001" name="AllTests">
  <testsuite name="FactorialTest" tests="2" failures="1" disabled="0" errors="0" time="0.001">
    <testcase name="withPositiveNumbers" status="run" time="0.001" classname="FactorialTest">
      <failure message="test2.cpp:7&#x0A;Value of: mm.factorial(5)&#x0A;  Actual: 1&#x0A;Expected: 120" type=""><![CDATA[test2.cpp:7
Value of: mm.factorial(5)
  Actual: 1
Expected: 120]]></failure>
    </testcase>
    <testcase name="withZero" status="run" time="0" classname="FactorialTest" />
  </testsuite>
</testsuites>
